apiVersion: v1
data:
  deploy: '{"defaultDeploymentMode":"RawDeployment"}'
  logger: '{}'
  storageInitializer: |-
    {
      "image": "kserve/storage-initializer:v0.16.0",
      "memoryRequest": "100Mi",
      "memoryLimit": "1Gi",
      "cpuRequest": "100m",
      "cpuLimit": "1"
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"deploy":"{\"defaultDeploymentMode\":\"Standard\"}\n","logger":"{\n  \"image\" : \"kserve/agent:v0.16.0\",\n  \"cpuRequest\" : \"50m\",\n  \"cpuLimit\" : \"500m\",\n  \"memoryRequest\" : \"64Mi\",\n  \"memoryLimit\" : \"256Mi\"\n}\n","storageInitializer":"{\n  \"image\" : \"kserve/storage-initializer:v0.16.0\",\n  \"cpuRequest\" : \"100m\",\n  \"cpuLimit\" : \"1\",\n  \"memoryRequest\" : \"100Mi\",\n  \"memoryLimit\" : \"1Gi\",\n  \"enableModelcar\" : false,\n  \"cpuModelcar\" : \"100m\",\n  \"memoryRequestModelcar\" : \"100Mi\",\n  \"memoryLimitModelcar\" : \"1Gi\"\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"inferenceservice-config","namespace":"kserve"}}
  creationTimestamp: "2026-02-08T21:19:13Z"
  name: inferenceservice-config
  namespace: kserve
  resourceVersion: "4914790"
  uid: f4bddf98-0595-406d-86ec-8a0c7b38bbdd
